/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    categories: Category;
    events: Event;
    photos: Photo;
    testimonials: Testimonial;
    'pricing-rows': PricingRow;
    inquiries: Inquiry;
    clients: Client;
    'checklist-templates': ChecklistTemplate;
    backstage: Backstage;
    'backstage-thumbnails': BackstageThumbnail;
    'testimonial-submissions': TestimonialSubmission;
    'testimonial-photos': TestimonialPhoto;
    logos: Logo;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    photos: PhotosSelect<false> | PhotosSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    'pricing-rows': PricingRowsSelect<false> | PricingRowsSelect<true>;
    inquiries: InquiriesSelect<false> | InquiriesSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    'checklist-templates': ChecklistTemplatesSelect<false> | ChecklistTemplatesSelect<true>;
    backstage: BackstageSelect<false> | BackstageSelect<true>;
    'backstage-thumbnails': BackstageThumbnailsSelect<false> | BackstageThumbnailsSelect<true>;
    'testimonial-submissions': TestimonialSubmissionsSelect<false> | TestimonialSubmissionsSelect<true>;
    'testimonial-photos': TestimonialPhotosSelect<false> | TestimonialPhotosSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'header-nav': HeaderNav;
    hero: Hero;
    'categories-intro': CategoriesIntro;
    about: About;
    'featured-offer': FeaturedOffer;
    'booking-cta': BookingCta;
    'testimonials-teaser': TestimonialsTeaser;
    'final-cta-footer': FinalCtaFooter;
    'site-settings': SiteSetting;
    booking: Booking;
  };
  globalsSelect: {
    'header-nav': HeaderNavSelect<false> | HeaderNavSelect<true>;
    hero: HeroSelect<false> | HeroSelect<true>;
    'categories-intro': CategoriesIntroSelect<false> | CategoriesIntroSelect<true>;
    about: AboutSelect<false> | AboutSelect<true>;
    'featured-offer': FeaturedOfferSelect<false> | FeaturedOfferSelect<true>;
    'booking-cta': BookingCtaSelect<false> | BookingCtaSelect<true>;
    'testimonials-teaser': TestimonialsTeaserSelect<false> | TestimonialsTeaserSelect<true>;
    'final-cta-footer': FinalCtaFooterSelect<false> | FinalCtaFooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    booking: BookingSelect<false> | BookingSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Who can log in to this dashboard. There should normally be just one account here — yours.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Your name (optional — for your own reference only).
   */
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * The types of photography you offer (Weddings, Portraits, Pets, etc.) — these show up as the tiles on the homepage and each one gets its own portfolio page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  _order?: string | null;
  /**
   * The category name, e.g. "Weddings".
   */
  name: string;
  /**
   * Turn off to hide this category from your site.
   */
  published?: boolean | null;
  slug: string;
  /**
   * One short line shown under the category name on the homepage. Up to 36 characters, so it stays on one line on phones.
   */
  blurb?: string | null;
  /**
   * The photo used for this category's tile on the homepage.
   */
  coverPhoto?: (number | null) | Photo;
  /**
   * The large banner photo shown at the top of this category's own page.
   */
  heroPhoto?: (number | null) | Photo;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Every photo you upload — the library that events, testimonials, and the homepage draw from.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos".
 */
export interface Photo {
  id: number;
  /**
   * A short, plain description of what's in the photo (e.g. "Bride and groom laughing during the first dance"). Used by screen readers for visually impaired visitors, and helps the photo show up in search results — every photo needs one.
   */
  alt: string;
  /**
   * An optional caption shown under the photo when someone clicks to view it larger.
   */
  caption?: string | null;
  /**
   * Which shoot this photo belongs to, if any.
   */
  event?: (number | null) | Event;
  /**
   * Only set this if the photo isn't part of a specific shoot above — for example, a category's cover photo.
   */
  category?: (number | null) | Category;
  /**
   * Check this to make the photo eligible for use on the homepage.
   */
  featured?: boolean | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Each album is one shoot (a wedding, a portrait session) and holds its photos. Albums show on their category's page, newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  /**
   * The name of this shoot, e.g. "Priya & Daniel's Wedding".
   */
  title: string;
  /**
   * Turn off to hide this album from your site.
   */
  published?: boolean | null;
  slug: string;
  /**
   * Which category this album belongs to. It shows on that category's page.
   */
  category: number | Category;
  /**
   * Optional. A short note shown under the album's title. Up to 70 characters, so it fits on two lines on phones.
   */
  description?: string | null;
  /**
   * Optional. The day of the shoot; its month and year show next to the album's title. Albums are listed newest first.
   */
  date?: string | null;
  sortDate?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Client quotes and reviews, shown on the Testimonials page. Pick which ones appear on your homepage in Testimonials Teaser.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: number;
  /**
   * The client's quote, word for word.
   */
  quote: string;
  /**
   * Who said it, e.g. "Priya & Daniel".
   */
  clientName: string;
  /**
   * Which category this testimonial relates to. Required — testimonials without one won't appear on the Testimonials page.
   */
  category: number | Category;
  /**
   * Which shoot this testimonial is about, if you'd like to link to it.
   */
  event?: (number | null) | Event;
  /**
   * An optional photo shown alongside this testimonial.
   */
  photo?: (number | null) | Photo;
  /**
   * An optional short line, e.g. "Wedding, June 2025".
   */
  context?: string | null;
  featured?: boolean | null;
  /**
   * Turn off to hide this testimonial from the live site.
   */
  published?: boolean | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Your packages and prices, shown in the Offers & pricing section of your homepage. Drag to set their order. To spotlight one in 'Popular right now', pick it on the Featured Offer page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-rows".
 */
export interface PricingRow {
  id: number;
  _order?: string | null;
  /**
   * The package name, e.g. "Wedding Day Coverage". Up to 28 characters, so it fits on two lines beside the price on phones.
   */
  title: string;
  /**
   * Turn off to hide this package from your site.
   */
  published?: boolean | null;
  /**
   * Which category this package belongs to. Its View gallery button opens that category's page.
   */
  category: number | Category;
  /**
   * The small word above the price, e.g. "From" or "Starting at". Up to 13 characters.
   */
  priceLead?: string | null;
  /**
   * Any text, e.g. "$2,800", "$450/hr" or "Custom quote". Up to 12 characters, so it leaves room for the name on phones.
   */
  priceAmount: string;
  /**
   * A sentence or two describing this package. Up to 100 characters, about three lines on a phone.
   */
  summary: string;
  features?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Optional. A few photos from this album show beside the package when it's in 'Popular right now', and its first photo is the thumbnail in this list. Only live albums in this package's category are listed.
   */
  album?: (number | null) | Event;
  gallery?: (number | Photo)[] | null;
  featured?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Every question and booking request submitted through the site's contact forms — your inbox for new client inquiries.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries".
 */
export interface Inquiry {
  id: number;
  /**
   * Whether this came in as a general question or a booking request.
   */
  type: 'question' | 'booking';
  inquiryType: 'booking' | 'question';
  questionHandled?: boolean | null;
  /**
   * Where this inquiry stands. You can change this right from the list below, no need to open the entry.
   */
  status: 'new' | 'contacted' | 'booked' | 'declined' | 'completed';
  /**
   * The client's name.
   */
  name: string;
  /**
   * The client's email address.
   */
  email: string;
  /**
   * The client's phone number, if they gave one.
   */
  phone?: string | null;
  /**
   * Link this inquiry to a Client record to track their history with you.
   */
  client?: (number | null) | Client;
  /**
   * What the client wrote.
   */
  message: string;
  /**
   * The date they asked about, if any.
   */
  preferredDate?: string | null;
  /**
   * Where this inquiry stands in the booking pipeline.
   */
  stage: 'lead' | 'planning' | 'prep' | 'shoot' | 'post' | 'wrapup';
  /**
   * Sub-status while this is in Post-Production.
   */
  postProductionStatus?: ('editing' | 'edited' | 'sent') | null;
  /**
   * Whether the client's testimonial has come in.
   */
  testimonialReceived?: boolean | null;
  /**
   * Whether this shoot has been added to the site.
   */
  addedToSite?: boolean | null;
  /**
   * Set automatically once the wrap-up checklist is complete — not something to edit directly.
   */
  archived?: boolean | null;
  /**
   * Which category this shoot belongs to.
   */
  category?: (number | null) | Category;
  /**
   * The confirmed date of the shoot.
   */
  shootDate?: string | null;
  /**
   * Whether the shoot date is locked in, not just a placeholder from the client's requested date.
   */
  shootDateConfirmed?: boolean | null;
  /**
   * When the finished photos are due to the client.
   */
  deliveryDeadline?: string | null;
  location?: {
    street?: string | null;
    city?: string | null;
    state?: string | null;
  };
  /**
   * The agreed price for this shoot.
   */
  price?: number | null;
  /**
   * Where payment stands for this shoot.
   */
  paymentStatus?: ('unpaid' | 'deposit' | 'paid') | null;
  /**
   * How this inquiry came in.
   */
  source?: ('website' | 'manual_social' | 'manual_email' | 'manual_referral') | null;
  /**
   * Freeform prep tasks for this shoot.
   */
  prepChecklist?:
    | {
        item?: string | null;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Freeform post-production tasks for this shoot.
   */
  postProductionChecklist?:
    | {
        item?: string | null;
        completed?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * The shoot this inquiry turned into, once you've created it. Leave empty until then — this is what lets you request a testimonial for this client.
   */
  event?: (number | null) | Event;
  /**
   * Whether a testimonial request email has been sent to this client. Set automatically — use the "Resend" option above rather than editing this directly.
   */
  testimonialRequestSent?: boolean | null;
  /**
   * When the testimonial request email was last sent. Filled in automatically.
   */
  testimonialRequestSentAt?: string | null;
  testimonialRequestToken?: string | null;
  /**
   * Which page of the site this was submitted from. Filled in automatically — not something to edit.
   */
  sourcePage?: string | null;
  /**
   * Your own private notes about this inquiry — the client never sees these.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Everyone who's booked or inquired — link an Inquiry to a Client to track repeat business.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  /**
   * The client's name.
   */
  name: string;
  /**
   * The client's email address.
   */
  email?: string | null;
  /**
   * The client's phone number.
   */
  phone?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
}
/**
 * Item lists reused across Prep and Post-Production checklists — one Standard template per type, plus optional per-category overrides.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-templates".
 */
export interface ChecklistTemplate {
  id: number;
  /**
   * Internal label shown in the admin list — not shown to clients.
   */
  name: string;
  /**
   * Which checklist this template fills.
   */
  type: 'prep' | 'postProduction';
  /**
   * Leave unset for the Standard template used by categories without their own.
   */
  category?: (number | null) | Category;
  items?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * The photos and video clips on your Backstage page. Drag to set their order; new ones go to the top.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage".
 */
export interface Backstage {
  id: number;
  _order?: string | null;
  /**
   * Optional. Shown under the tile and in the viewer. Left blank, it comes from the file name. Up to 30 characters.
   */
  title?: string | null;
  /**
   * Turn off to hide this item from your Backstage page.
   */
  published?: boolean | null;
  /**
   * Optional. Two lines show under the tile; all of it shows in the viewer. Up to 150 characters.
   */
  caption?: string | null;
  /**
   * Made automatically from a frame of the video. To use your own image, remove this and upload one; remove yours to go back to the automatic one.
   */
  poster?: (number | null) | BackstageThumbnail;
  type: 'video' | 'reel_embed';
  reelUrl?: string | null;
  thumbnail?: (number | null) | Photo;
  order?: number | null;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  deletedAt?: string | null;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Thumbnails for your Backstage videos. Most are made automatically from the video; you can upload your own from a video's editor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage-thumbnails".
 */
export interface BackstageThumbnail {
  id: number;
  /**
   * Made automatically from the video.
   */
  generated?: boolean | null;
  item?: (number | null) | Backstage;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Testimonials clients have submitted through their request link — review, correct, and publish the ones you'd like to show on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial-submissions".
 */
export interface TestimonialSubmission {
  id: number;
  /**
   * The inquiry this testimonial request was sent for.
   */
  inquiry: number | Inquiry;
  /**
   * Carried forward from the linked inquiry at submission time.
   */
  name: string;
  /**
   * Carried forward from the linked inquiry at submission time.
   */
  email: string;
  /**
   * Carried forward from the linked event's category at submission time, if it had one. Correct it here if needed before publishing.
   */
  category?: (number | null) | Category;
  /**
   * Carried forward from the linked inquiry at submission time. Correct it here if needed before publishing.
   */
  event?: (number | null) | Event;
  /**
   * The testimonial, word for word as the client wrote it.
   */
  testimonialText: string;
  /**
   * Photos the client attached, if any. Private until you promote one into the Photos library when publishing.
   */
  photos?: (number | TestimonialPhoto)[] | null;
  /**
   * An Instagram/Facebook link the client shared, if any. Reference only — not part of the published testimonial.
   */
  socialLink?: string | null;
  /**
   * Anything the client wanted you to know privately. Visible only to you here — never copied into a published testimonial.
   */
  privateNotes?: string | null;
  /**
   * Whether this submission has been published as a real Testimonial yet.
   */
  status: 'pending' | 'published';
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos clients attach to a testimonial submission — private until you promote one into the Photos library from the submission's review screen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial-photos".
 */
export interface TestimonialPhoto {
  id: number;
  inquiry?: (number | null) | Inquiry;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Logo files uploaded from Site Settings. Only the one picked there is shown on the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  prefix?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    display?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'events';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'photos';
        value: number | Photo;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'pricing-rows';
        value: number | PricingRow;
      } | null)
    | ({
        relationTo: 'inquiries';
        value: number | Inquiry;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'checklist-templates';
        value: number | ChecklistTemplate;
      } | null)
    | ({
        relationTo: 'backstage';
        value: number | Backstage;
      } | null)
    | ({
        relationTo: 'backstage-thumbnails';
        value: number | BackstageThumbnail;
      } | null)
    | ({
        relationTo: 'testimonial-submissions';
        value: number | TestimonialSubmission;
      } | null)
    | ({
        relationTo: 'testimonial-photos';
        value: number | TestimonialPhoto;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  _order?: T;
  name?: T;
  published?: T;
  slug?: T;
  blurb?: T;
  coverPhoto?: T;
  heroPhoto?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  published?: T;
  slug?: T;
  category?: T;
  description?: T;
  date?: T;
  sortDate?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "photos_select".
 */
export interface PhotosSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  event?: T;
  category?: T;
  featured?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  quote?: T;
  clientName?: T;
  category?: T;
  event?: T;
  photo?: T;
  context?: T;
  featured?: T;
  published?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-rows_select".
 */
export interface PricingRowsSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  published?: T;
  category?: T;
  priceLead?: T;
  priceAmount?: T;
  summary?: T;
  features?:
    | T
    | {
        text?: T;
        id?: T;
      };
  album?: T;
  gallery?: T;
  featured?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "inquiries_select".
 */
export interface InquiriesSelect<T extends boolean = true> {
  type?: T;
  inquiryType?: T;
  questionHandled?: T;
  status?: T;
  name?: T;
  email?: T;
  phone?: T;
  client?: T;
  message?: T;
  preferredDate?: T;
  stage?: T;
  postProductionStatus?: T;
  testimonialReceived?: T;
  addedToSite?: T;
  archived?: T;
  category?: T;
  shootDate?: T;
  shootDateConfirmed?: T;
  deliveryDeadline?: T;
  location?:
    | T
    | {
        street?: T;
        city?: T;
        state?: T;
      };
  price?: T;
  paymentStatus?: T;
  source?: T;
  prepChecklist?:
    | T
    | {
        item?: T;
        completed?: T;
        id?: T;
      };
  postProductionChecklist?:
    | T
    | {
        item?: T;
        completed?: T;
        id?: T;
      };
  event?: T;
  testimonialRequestSent?: T;
  testimonialRequestSentAt?: T;
  testimonialRequestToken?: T;
  sourcePage?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "checklist-templates_select".
 */
export interface ChecklistTemplatesSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  category?: T;
  items?:
    | T
    | {
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage_select".
 */
export interface BackstageSelect<T extends boolean = true> {
  _order?: T;
  title?: T;
  published?: T;
  caption?: T;
  poster?: T;
  type?: T;
  reelUrl?: T;
  thumbnail?: T;
  order?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  deletedAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "backstage-thumbnails_select".
 */
export interface BackstageThumbnailsSelect<T extends boolean = true> {
  generated?: T;
  item?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial-submissions_select".
 */
export interface TestimonialSubmissionsSelect<T extends boolean = true> {
  inquiry?: T;
  name?: T;
  email?: T;
  category?: T;
  event?: T;
  testimonialText?: T;
  photos?: T;
  socialLink?: T;
  privateNotes?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonial-photos_select".
 */
export interface TestimonialPhotosSelect<T extends boolean = true> {
  inquiry?: T;
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  prefix?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        display?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * The menu bar at the top of every page: the links people see and the 'Book' button on the right. Your logo on the left is set in Site Settings.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav".
 */
export interface HeaderNav {
  id: number;
  /**
   * The links across the top of your site. Drag to reorder.
   */
  navLinks?:
    | {
        label: string;
        href:
          | '/'
          | '/#categories'
          | '/#about'
          | '/#offers'
          | '/#hot-offer'
          | '/#booking-cta'
          | '/#instagram'
          | '/#testimonials'
          | '/booking'
          | '/backstage'
          | '/testimonials'
          | '/privacy-policy'
          | '/terms';
        id?: string | null;
      }[]
    | null;
  bookLabel?: string | null;
  /**
   * Where the 'Book' button sends people. Locked to the booking page.
   */
  bookHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The big image and headline at the very top of the homepage — the first thing anyone sees.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  /**
   * Optional. Pick the photos that rotate behind your headline, then drag them into order (up to 8). Leave empty to use your category cover photos. Each photo is cropped around its focal point — set that on the photo itself.
   */
  heroPhotos?: (number | Photo)[] | null;
  /**
   * The large title text over the homepage photos.
   */
  headline: string;
  /**
   * The smaller line of text under the headline.
   */
  subhead?: string | null;
  /**
   * The text on the button under the headline. Up to 24 characters, so it stays on one line on phones.
   */
  ctaLabel?: string | null;
  /**
   * Where the button sends people. Locked to the booking section.
   */
  ctaHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The heading above the row of category photos (Weddings, Portraits, etc.) on the homepage.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories-intro".
 */
export interface CategoriesIntro {
  id: number;
  /**
   * The title text above the category photos. Up to 20 characters, so it stays on one line on phones.
   */
  heading: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The 'About' section on the homepage — your photo, your bio and the quick links below it.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about".
 */
export interface About {
  id: number;
  /**
   * The title above this section.
   */
  heading: string;
  /**
   * Your photo, shown next to the bio. Upright/portrait-shaped photos work best.
   */
  portrait?: (number | null) | Photo;
  /**
   * The paragraph(s) about you and your work, shown next to your photo.
   */
  bio?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  quickLinks?:
    | {
        label: string;
        title: string;
        href:
          | '/'
          | '/#categories'
          | '/#about'
          | '/#offers'
          | '/#hot-offer'
          | '/#booking-cta'
          | '/#instagram'
          | '/#testimonials'
          | '/booking'
          | '/backstage'
          | '/testimonials'
          | '/privacy-policy'
          | '/terms';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The 'Popular right now' spotlight on your homepage. Pick which package to feature below.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-offer".
 */
export interface FeaturedOffer {
  id: number;
  /**
   * Pick the package to spotlight, or None to hide this section.
   */
  featuredPackage?: (number | null) | PricingRow;
  /**
   * The title above the featured package. Up to 20 characters, so it stays on one line on phones.
   */
  heading: string;
  /**
   * The small highlighted tag on the featured package, here and on its row in Offers & pricing. Up to 24 characters.
   */
  badgeLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The 'Ready when you are' section on your homepage that invites people to book a session, with a line under the button: your text, followed by your contact details as links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-cta".
 */
export interface BookingCta {
  id: number;
  /**
   * The title of this section. Up to 20 characters, so it stays on one line on phones.
   */
  heading: string;
  /**
   * The line of text under the title. Up to 110 characters, so it stays within three lines on phones.
   */
  subheading?: string | null;
  /**
   * The text on the button, which goes to your booking page. Up to 26 characters, so it stays on one line.
   */
  ctaLabel?: string | null;
  /**
   * Where the button sends people. Locked to the booking page.
   */
  ctaHref?: string | null;
  /**
   * Shown before your contact details, e.g. "Prefer to reach out directly?" Up to 40 characters. Leave empty to show just the links.
   */
  contactLeadIn?: string | null;
  showEmail?: boolean | null;
  showPhone?: boolean | null;
  showInstagram?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The 'In their words' section on your homepage. Pick up to 4 testimonials to show.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-teaser".
 */
export interface TestimonialsTeaser {
  id: number;
  /**
   * Pick up to 4 testimonials and drag them into the order you want. With none picked, this section is hidden.
   */
  testimonials?: (number | Testimonial)[] | null;
  /**
   * The title above the quotes. Up to 20 characters, so it stays on one line on phones.
   */
  heading: string;
  /**
   * The link to your full Testimonials page. Up to 30 characters, so it stays on one line on phones.
   */
  linkLabel?: string | null;
  /**
   * Where that link goes. Locked to the testimonials page.
   */
  linkHref?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The bottom of every page: your closing line and button, your footer links and which contact details to show. Privacy Policy, Terms and the copyright line are always there.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "final-cta-footer".
 */
export interface FinalCtaFooter {
  id: number;
  /**
   * The message above the button. Up to 48 characters, so it stays within two lines on phones.
   */
  signOffLine: string;
  /**
   * The text on the button, which goes to your booking page. Up to 26 characters, so it stays on one line.
   */
  ctaLabel?: string | null;
  /**
   * Where the button sends people. Locked to the booking page.
   */
  ctaHref?: string | null;
  footerNav?:
    | {
        label: string;
        href:
          | '/'
          | '/#categories'
          | '/#about'
          | '/#offers'
          | '/#hot-offer'
          | '/#booking-cta'
          | '/#instagram'
          | '/#testimonials'
          | '/booking'
          | '/backstage'
          | '/testimonials'
          | '/privacy-policy'
          | '/terms';
        id?: string | null;
      }[]
    | null;
  showEmail?: boolean | null;
  showPhone?: boolean | null;
  showInstagram?: boolean | null;
  /**
   * Never shown on phones, where it can't be scanned.
   */
  showQrCode?: boolean | null;
  copyrightName?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Studio name, logo, email, phone, Instagram, and the small icon/preview image used when the site is shared or shows up in a browser tab. These values are reused in several places across the site.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * Your studio's name, used across the site.
   */
  siteName: string;
  /**
   * Your logo, shown at the top-left of every page and in the footer. Best as a PNG with a transparent background. Leave empty to show your studio name as text instead.
   */
  logo?: (number | null) | Logo;
  /**
   * How tall your logo is at the top of the page. Phones show it a little smaller.
   */
  logoHeight?: number | null;
  /**
   * The small icon shown in a browser tab. Works best as a simple square image.
   */
  favicon?: (number | null) | Photo;
  /**
   * The preview image shown when the site is shared on social media or messaging apps.
   */
  ogImage?: (number | null) | Photo;
  /**
   * A short description of the preview image above, for screen readers and search engines.
   */
  ogImageAlt?: string | null;
  /**
   * How people reach you — shown in the footer and the homepage booking section.
   */
  contact?: {
    /**
     * Your contact email address.
     */
    email?: string | null;
    /**
     * Leave empty to keep your number off the site. US numbers can be typed any way, e.g. 555 123 4567; for other countries start with + and the country code, spaced the way you want it shown.
     */
    phone?: string | null;
    phoneDisplay?: string | null;
    phoneHref?: string | null;
  };
  /**
   * Your Instagram account, shown in the footer, the homepage Instagram section and the booking section.
   */
  instagram?: {
    /**
     * With or without the @, e.g. @hamlettvisuals. Your profile link is made from it. Leave empty to hide Instagram links.
     */
    handle?: string | null;
    url?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The heading, intro paragraph, and "How it works" steps on the Book a session page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking".
 */
export interface Booking {
  id: number;
  /**
   * The title at the top of the Booking page.
   */
  heading: string;
  /**
   * The short paragraph under the heading.
   */
  intro: string;
  /**
   * The numbered "How it works" steps shown above the booking form.
   */
  steps?:
    | {
        /**
         * A short step title, e.g. "Submit your request".
         */
        title: string;
        /**
         * One line explaining the step, e.g. "I'll follow up within 48 hours."
         */
        description: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header-nav_select".
 */
export interface HeaderNavSelect<T extends boolean = true> {
  navLinks?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  bookLabel?: T;
  bookHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  heroPhotos?: T;
  headline?: T;
  subhead?: T;
  ctaLabel?: T;
  ctaHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories-intro_select".
 */
export interface CategoriesIntroSelect<T extends boolean = true> {
  heading?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about_select".
 */
export interface AboutSelect<T extends boolean = true> {
  heading?: T;
  portrait?: T;
  bio?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        title?: T;
        href?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "featured-offer_select".
 */
export interface FeaturedOfferSelect<T extends boolean = true> {
  featuredPackage?: T;
  heading?: T;
  badgeLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking-cta_select".
 */
export interface BookingCtaSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  ctaLabel?: T;
  ctaHref?: T;
  contactLeadIn?: T;
  showEmail?: T;
  showPhone?: T;
  showInstagram?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials-teaser_select".
 */
export interface TestimonialsTeaserSelect<T extends boolean = true> {
  testimonials?: T;
  heading?: T;
  linkLabel?: T;
  linkHref?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "final-cta-footer_select".
 */
export interface FinalCtaFooterSelect<T extends boolean = true> {
  signOffLine?: T;
  ctaLabel?: T;
  ctaHref?: T;
  footerNav?:
    | T
    | {
        label?: T;
        href?: T;
        id?: T;
      };
  showEmail?: T;
  showPhone?: T;
  showInstagram?: T;
  showQrCode?: T;
  copyrightName?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  logo?: T;
  logoHeight?: T;
  favicon?: T;
  ogImage?: T;
  ogImageAlt?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        phoneDisplay?: T;
        phoneHref?: T;
      };
  instagram?:
    | T
    | {
        handle?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "booking_select".
 */
export interface BookingSelect<T extends boolean = true> {
  heading?: T;
  intro?: T;
  steps?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}